### ISSUE TITLE
Hello, Social Media!

### ISSUE THREAD

**Issue by bGZo** [bGZo/bgzo.github.io#3]
在电影 监视资本主义:智能陷阱([The Social Dilemma](https://movie.douban.com/subject/34960008/)) 中, 他们这样形容如今用户面对的互联网现状:

> - 他们像蜘蛛一样测试你的神经, 这是很恐怖的
> - 你的焦虑, 脆弱和抑郁是不是这些 Social Media 带来的. 
> - 你的自我处理情绪的能力在下降
> - If you're not paying for the product，then you are the product.
> - They sell certainty.
> - You have to have great predictions. You need a lot of data.
> - " Any sufficiently advanced technology is indistinguishable from magic." -- Arthur C. Clarke
> - " There are only two industries that call their customers 'users': illegal drugs and software." -- Edward Tufte

<br/>

Q: 被监听妄想症?

> 你不得不承认这个世界对思想的控制大大的超越人类自诞生以来所有时代。你会发现自己越来越孤独，而那些叫不醒的人反而会觉得你是异类. -- [广告与监听](https://www.v2ex.com/t/799831)

**Comment by bGZoCg** [comment]
[1/n] 暂时无法注销账户:

- 七牛云

**Comment by bGZoCg** [comment]
[2/n] **Email**
<br/>
一共有四个邮箱:
1. Google
2. Outlook
3. IMU Education
4. QQ

现在保留永久私人Google邮箱, 一般给身边的亲友,老师,同学; 可换地址工作邮箱Outlook, 工作面试招聘等正式场合. 查看为一天一次. IMU学生邮箱保持学校的联络以及学生产品优惠;一学期查看一次. 垃圾试水测试全抛给常年不看的qq邮箱.

**Comment by bGZoCg** [comment]
[3/n] 信息加密:

关于社交媒体隐匿信息, 查看我的[博文-Wechat Name Change](http://dfslfh.cn/blog/posts/210305-wechat-name-change/)

**Comment by bGZoCg** [comment]
[4/n] **Articles Collections**

- [数据不是石油](https://www.solidot.org/story?sid=65706)
    > 没有生命力的石油是可以随便出口的，哪怕是敌对的国家，也不在意两国互换石油。但是数据不一样，数据的生命力让数据的迁移和人口的迁移没有什么两样。如果人类到某国需要签证，那么数据也需要签证。

**Comment by bGZoCg** [comment]
[5/n] Private Storage:

- **[学付宝]**: `/storage/emulated/0/xuepay/ServerAvatarImage.jpg`

**Comment by bGZoCg** [comment]
[6/n]: Toturials
 
Mostly in Chinese use a phone app to unsubscribe, not all platform?!

- [微信, QQ, 微博, 淘宝, 支付宝, 京东, 百度, 网易](https://sspai.com/post/43381).

**Comment by bGZoCg** [comment]
[1/n] 注销队列

十年前, 我以拥有网站账号数量而炫耀, 发疯似的把自己的隐私数据塞给社交媒体; 十年后, 我为我残留在网络上的快照而倍感焦虑, 疑神疑鬼地寻找注销账户的入口, 下面是自己的注销日志:

- **210101**  注销QQ空间(官方[入口](http://imgcache.qq.com/qzone/web/qzone_submit_close.html). chrome [导出插件](https://chrome.google.com/webstore/detail/qq空间导出助手/aofadimegphfgllgjblddapiaojbglhf)), 关闭朋友圈
- **210211**  注销迅雷, 喜马拉雅, 微博, FB, IG
- **210301**  注销抖音, 最右, 再度申请微博
- **210313**  注销拼多多分号, 保持微信登录使用
- **210319**  注销Amap, Kugou, ~~退出网易云登录.~~
- **210322**  注销京东白条([和自己信用贷款挂钩](https://www.v2ex.com/t/442257)) 
- **210415**  购买 VMOS Pro, ~~将 QQ, Wecha, Meiturn, Pindodo, Ele, Taobao 等软件置于虚拟机中~~.
- **210511**  购买 Samsung 备用机, 开始彻底放飞自我, Vmos 只用 Root 应用和色情应用.
- **210727**  注销微博, 扇贝编程.
- **210823**  注销 CSDN.
- **210823**  注销 VIVO 账号.
- **210923**  注销码云账号
- **210927**  豆瓣换绑 GV 被永久禁言, 之后写邮件请求解封, 最后注销. ([导出你的数据](https://chrome.google.com/webstore/detail/%E8%B1%86%E4%BC%B4%EF%BC%9A%E8%B1%86%E7%93%A3%E8%B4%A6%E5%8F%B7%E5%A4%87%E4%BB%BD%E5%B7%A5%E5%85%B7/ghppfgfeoafdcaebjoglabppkfmbcjdd)
- **211123**  注销有道词典
- **Logout Queues**:
    - Todo:
        - 京东
    - Cannot:
        - 七牛云

**Comment by bGZoCg** [comment]
[3/n] Email
一共有四个邮箱: `Google`, `Outlook`, `IMU Education`, `QQ`. 现在保留永久私人Google邮箱, 一般给身边的亲友,老师,同学; 可换地址工作邮箱Outlook, 工作面试招聘等正式场合. 查看为一天一次. IMU学生邮箱保持学校的联络以及学生产品优惠;一学期查看一次. 垃圾试水测试全抛给常年不看的qq邮箱.

**Comment by bGZoCg** [comment]
[3/n] 信息加密:

个人常常使用 base64 加密, 使用密码管理器 Bitwarden

**Comment by bGZoCg** [comment]
[4/n] Private Storage:

看看安卓拉的 Sh*t, 只放些目前常用到的目录地址:

- **[学付宝]**: `/storage/emulated/0/xuepay/ServerAvatarImage.jpg`
- **[Wechat]**: `/storage/emulated/0/Android/data/com.tencent.mm/MicroMsg/Download`
- **[QQ]**: `/storage/emulated/0/Android/data/com.tencent.mobileqq/Tencent/QQfile_recv`

**Comment by bGZoCg** [comment]
[5/n] Related Links

1. [APPLE - ZH - 个人数据的一天 - 记父女公园一日游](https://www.apple.com.cn/privacy/docs/A_Day_in_the_Life_of_Your_Data.pdf)

    > 跟踪器就内嵌在你每天使用的 app 中: 每一款 app 平均含有 6 个跟踪器[1], 大多数热门的 Android 和 iOS app 中都含有嵌入式跟踪器 [2] [3].
    >
    > 1. Competition & Markets Authority, “Online platforms and digital advertising,” July 1, 2020
    >
    > 2. AppCensus, “1,000 Mobile Apps in Australia: A Report for the ACCC,” September 24, 2020.
    >
    > 3. Binns, Reuben, Ulrik Lyngs, et al., “Third Party Tracking in the Mobile Ecosystem,” Proceedings of the 10th ACM Conference on Web Science, 2018, pp. 23-31.
    >
    > 跟踪器通常会被嵌入到可帮助开发者构建 app 的第三方代码中。通过添加追踪器，开发者还允许第三方对你在不同 app 中与其共享的数据进行收集，并与已收集到的其他关于你的数据相关联。
    >
    > 数据代理商收集、出售、许可，或以其他方式向第三方披露个人信息，而他们与被采集信息的特定人群并无直接联系。
    >
    > 每一天的每个小时中，在网络上向用户 展示的数字广告数以亿计[1] [2] [3], 在广告加载所需的几毫秒内，就会进行实时竞拍，此时广告商通常就根据跟踪得到的个人数据对广告位展开竞价[4] [5].
    >
    > 1. Edwards, Jim, “Here’s The Staggering Number of Ads Facebook Serves On Its Exchange Every Day,” Business Insider, November 9, 2012.
    > 12. Kim, Larry, “How Many Ads Does Google Serve In A Day?,” Business 2 Community, November 2, 2012.
    > 13. Deighton, John, and Leora Kornfeld, “The Socioeconomic Impact of Internet Tracking,” Interactive Advertising Bureau, February 2020.
    > 14. Hwang, Tim, Subprime Attention Crisis: Advertising and the Time Bomb at the Heart of the Internet, FSG Originals, October 13, 2020.
    > 15. Australian Competition and Consumer Commission, “Digital advertising services inquiry - Interim report,” December 2020.
    >
    > 信息交换可能会流向广告网络、广告发布者、归因和监测服务提供商、数据代理商、其他私有公司，甚至是政府机构[1] [2] [3] [4] [5] 由于将个人数据用于收集信息时所明示的用途之外，已有多家社交媒体和广告技术公司面临着或已支付数百万美元的罚款[6] [7] [8] [9]
    >
    > 1. Competition & Markets Authority, “Online platforms and digital advertising,” July 1, 2020.
    > 2. Australian Competition and Consumer Commission, “Digital advertising services inquiry - Interim report,” December 2020.
    > 3. Cox, Joseph, “The IRS Is Being Investigated for Using Location Data Without a Warrant,” Vice, October 6, 2020.
    > 41. Cox, Joseph, “How the U.S. Military Buys Location Data from Ordinary Apps,” Vice, November 16, 2020.
    > 42. Cox, Joseph, “CBP Bought ‘Global’ Location Data from Weather and Game Apps,” Vice, October 6, 2020.
    > 6. Federal Trade Commission, “FTC Imposes $5 Billion Penalty and Sweeping New Privacy Restrictions on Facebook,” July 24, 2019.
    > 23. Chin, Kimberly, “Twitter Could Pay FTC Fine Over Alleged Privacy Violations,” The Wall Street Journal, August 3, 2020.
    > 24. Satariano, Adam, “Google Is Fined $57 Million Under Europe’s Data Privacy Law,” The New York Times, January 21, 2019.
    > 25. Schiffer, Zoe, “Period tracking app settles charges it lied to users about privacy,” The Verge, January 13, 2021.

2. [大家平时都是怎么保护隐私的？-V2EX](https://www.v2ex.com/t/771550)

    > - 除了 1Password （最近考虑用 LAN 同步），Notion，iCloud，VPS，好像基本都不怎么用跟云相关的产品，选择新软件或者产品的时候，会查看公司口碑，是否符合 GDRP 等；
    > - 最近在电梯里，地铁里，咖啡厅等公开地方，输入密码会注意头上有没有摄像头；
    > - 电子产品离开视野，必定手动锁定；
    > - 每个账号绑定的邮箱都是独立的，采用随机 UUDI 的形式，哪里泄漏马上就知道；

3. [数据不是石油](https://www.solidot.org/story?sid=65706)

     > 没有生命力的石油是可以随便出口的，哪怕是敌对的国家，也不在意两国互换石油。但是数据不一样，数据的生命力让数据的迁移和人口的迁移没有什么两样。如果人类到某国需要签证，那么数据也需要签证。 

4. [微信, QQ, 微博, 淘宝, 支付宝, 京东, 百度, 网易 注销指南](https://sspai.com/post/43381), 
    Phone > Everything? Excuse me??? why just could use a  app to unsubscribe, not all platform?!  

5. [V2EX - 注销账号，太难了](https://www.v2ex.com/t/799827#14)

     > .......即便侥幸注销成功，也是假删除，都是搞 it 的不需要多说了。这就是赛博朋克，你死了，但是你的数据载体永生。那么，既然无法注销，那么应对？我选择给他们投毒。就像用不重复的大文件占用某些云盘的空间一样（百度云），既然我不喜欢你，你还拼命膈应我，那么我就只能“以彼之道还施彼身”了。怎么投毒呢？比如微信，既然不让注销，那么我拼命发朋友圈，所有内容都是毫不相干但是又看起来像是广告的，**总之干扰腾讯他们的数据分析，模糊你原来的数据，就行了**.......

6. [V2EX - 面对互联网公司对用户隐私的手越伸越长，我们能做些什么？](https://www.v2ex.com/t/796421)

    > ......有些工具类的 app，很显然他们会要求超过所需的权限，但是我也懒得去下另一个 app 了，用完就删了。有些国民级 app，**他们有的是办法通过埋点，数据联盟，在不申请过多权限的情况下窃取你的隐私，你咋办？**难道能不用？算了算了，累了.......
    >
    > .......想做个针对监听隐私的投毒软件: **随机播放一堆文字给智能音箱; 随机访问淘宝污染用户画像; 随机访问网页，污染历史记录; 随机刷定位等等;随机抖音搜视屏污染用户画像**. 你听归你听，听的真不真又是另外一码事，感觉这软件商业收费应该也有人用。和爬虫中的投毒机制差不多.......

6. [V2EX - 广告与监听](https://www.v2ex.com/t/799831)

   > .......假设你的 WiFi 没有开启随机 MAC 地址（即使开启了，还得考验操作系统厂商的节操），那么你去过的大多数地方做了停留就能被探针记录，不需要你连接任何热点，这样的探针无处不在。这些探针厂商基本是拿着数据瞎卖的，你也锤不了他们，然后不知道过了多少手大厂肯定能拿到这些数据，他们的模型接着就能够把你和所有在你这台手机登陆过的账号匹配起来。于是就能做基于地理位置的行为分析，包括时间和空间上的.......
